language: clojure
script: lein doo node "server-tests" once
notifications:
  email:
    recipients:
      - filip@district0x.io
      - juan@district0x.io
      - mike@district0x.io
    on_success: change # default: change
    on_failure: always # default: always
before_install:
 - sudo add-apt-repository --yes ppa:ethereum/ethereum
 - sudo apt-get -qq update
before_script:
  - sudo apt-get --yes install solc
  - lein solc
  - npm install -g ganache-cli
  - ganache-cli -p 8549 > /dev/null &
  - wget https://dist.ipfs.io/ipfs-update/v1.5.2/ipfs-update_v1.5.2_linux-amd64.tar.gz -O ipfs-update.tar.gz
  - tar -xzf ipfs-update.tar.gz
  - ipfs-update/ipfs-update install latest
  - ipfs init 
  - ipfs daemon > /dev/null &
