language: clojure
script: lein doo node "server-tests" once
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
    - filip@district0x.io
    - juan@district0x.io
    - mike@district0x.io
  slack:
    on_success: always
    on_failure: always    
    secure: rm32X0IZzMDcSpYcuc9BlHJ7zlFlUZMOBlIV6p4cXD1AbfRKTVE6+tfPL5UGJCmDUL91Kexnp/PYeFqcy17mtZTCDfMgliemSjGT48Tw3CENCOWgLED4nMXqbIh4HNy1KuZkc4wlvDhxXAXs7BTzMNP3Mi/QQF9GlxgSXl0b+hdKUd4ckTxyWYJ3XCHPwRx5vsvsr+xRgXw3oTFZlnORur4J4V79v/dGgvUdJZmNUJIiSkylkv4nJZJrpFs5l9FCRDnyv0KCZ0aDvaEm/v9XEuQ+HrucEC8S/ye7BsGlAv7UrF2Y/eZVyZGACI9B+916lozAFIRb2fz3aC1SgBP+n7MCmDvtYossFkf5e5WcHHmXYvO6rBgVYjl7p4JDen8cxrbQGYaYYHkSgcQMPt1P0ZfhvW3QmMvoF/tOuYZpeFCA4kwtH03pK607KDKcpeYLYVvSVDqUvf79p7aLIYry/WrDsvxXCyH0/d8pUzM9AkBwsBSDe95whJAzEJ5TJQ5InryCDBM40mENVcjbet33rjj/a496bSu6MD0pfxovUzxnzHvN5XNE3JxmEFTAKXd9cD02qK08JyZRQRtupqYe1mN/qSt3sDAKTfPQA6HVMmVsJBKae3xfJQGUJibeCRjR0cYnCIv7A3xPGocdaRsyYU31I0T1FaLnlyfp7mT6VHY=
before_install:
- sudo add-apt-repository --yes ppa:ethereum/ethereum
- sudo apt-get -qq update
before_script:
- sudo apt-get --yes install solc
- lein solc
- npm install -g ganache-cli
- ganache-cli -p 8549 > /dev/null &
- wget https://dist.ipfs.io/ipfs-update/v1.5.2/ipfs-update_v1.5.2_linux-amd64.tar.gz
  -O ipfs-update.tar.gz
- tar -xzf ipfs-update.tar.gz
- ipfs-update/ipfs-update install latest
- ipfs init
- ipfs daemon > /dev/null &
